### ISSUE TITLE
Django 1.10 compatibility

### ISSUE THREAD

**Issue by pawelad** [arthanson/django-genericadmin#39]
The module does not work on Django 1.10, because use of patterns is [deprecated since Django 1.8](https://docs.djangoproject.com/en/1.9/ref/urls/#patterns):

```python
  File "/.../python2.7/site-packages/genericadmin/admin.py", line 5, in <module>
    from django.conf.urls import patterns, url
ImportError: cannot import name patterns
```

**Comment by ifigueroa** [comment]
Any updates on this issue? It seems like all its needed is to replace the "patterns" with a single list.

**Comment by pawelad** [comment]
Master actually fixes this (https://github.com/arthanson/django-genericadmin/commit/330463972344dc86e102c7f689023ca442b1558b) but it was never released. There is also #43 which tackles other Django 1.10 issues.

You could install directly from GitHub I guess, but I would consider this project abandoned.

**Comment by arthanson** [comment]
new release should fix this
